### ISSUE TITLE
Support additional MongoDB configuration properties

### ISSUE THREAD

**Issue by james-r-smith** [eclipse/jnosql-diana-driver#115]
Currently, MongoDB configuration only offers a configuration for address. In addition, you have the ability to pass in a [MongoClient](https://github.com/eclipse/jnosql-diana-driver/blob/0.0.8/mongodb-driver/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentConfiguration.java#L78), but it is not using the proper MongoClient (`com.mongodb.MongoClient` instead of `com.mongodb.client.MongoClient`). Also, the passing of MongoClient will not currently work with `org.jnosql.artemis.ConfigurationUnit` as well.

Issue will cover discussion on adding additional properties, defining the best format for the properties, and fixing the MongoClient parameter to use the proper class.

**Comment by james-r-smith** [comment]
Also, there are some [spelling mistakes](https://github.com/eclipse/jnosql-diana-driver/blob/master/mongodb-driver/src/main/java/org/jnosql/diana/mongodb/document/DocumentQueryConversor.java#L29) that would be great to fix as well. 😅

**Comment by otaviojava** [comment]
Hey, @james-r-smith did you need some help on this?
Please, let me know.
