### ISSUE TITLE
ArangoDB options

### ISSUE THREAD

**Issue by mxmind** [eclipse/jnosql-diana-driver#121]
Hi, 
I'm very interested to use your product. 
The following questions are blocking me to totally switch on it, because we have a ton of queries depend on that:
- Is it possible to add the Query options, while the AQL query is being prepared?
- Is it possible to add the options to modify a graph traversal queries behavior?

This is an snippet from [ArangoDB documentation](https://docs.arangodb.com/3.4/AQL/Graphs/Traversals.html):
```java
[WITH vertexCollection1[, vertexCollection2[, ...vertexCollectionN]]]
FOR vertex[, edge[, path]]
  IN [min[..max]]
  OUTBOUND|INBOUND|ANY startVertex
  GRAPH graphName
  [PRUNE pruneCondition]
  [OPTIONS options]
```

**Comment by otaviojava** [comment]
Hey.
We have this param values:

https://github.com/eclipse/jnosql-diana-driver/blob/master/arangodb-driver/src/main/java/org/jnosql/diana/arangodb/document/ArangoDBDocumentCollectionManager.java#L39

The allows with several parameters:

The implementation uses a wrapper from the official driver:

https://github.com/eclipse/jnosql-diana-driver/blob/master/arangodb-driver/src/main/java/org/jnosql/diana/arangodb/document/DefaultArangoDBDocumentCollectionManager.java#L118L126

This method exacly: http://arangodb.github.io/arangodb-java-driver/javadoc-4_0/index.html

Does it help?

**Comment by otaviojava** [comment]
About the Graph, there is a support to Graph with Apache Tinkerpop:

https://dzone.com/articles/arangodb-one-corequery-language-and-multiple-data

**Comment by mxmind** [comment]
Hi @otaviojava, I meant a bit different.
The ArangoDB query method and also other ones have a method argument which is AQL query options. Just look on this snippet, this parameter is omitted. But this is very useful to adjust queries.
```java
ArangoCursor<BaseDocument> result = arangoDB.db(database).query(query, values, null, BaseDocument.class);
```
For example, a developer can use them to create a page query and return the count of total elements affected by the query.

**Comment by otaviojava** [comment]
Sure, that makes sense.
However, the API won't be able to convert to a native communication entity once they don't know how to convert it.

What do you think if you add a new method of this way:

```java
<T> List<T> aql(String query, Map<String, Object> values, Class<T> typeClass);
```

**Comment by mxmind** [comment]
@otaviojava Does will the typeClass argument be properly applied to the aql result to map latter to BigDecimal or String? If that true, the problem is solved.

**Comment by otaviojava** [comment]
Yes, it will:

```java
public <T> List<T> aql(String query, Map<String, Object> values, Class<T> typeClass) {
       ArangoCursor<T> result = arangoDB.db(database).query(query, values, null, typeClass);
        return result.asListRemaining();
    }
```

**Comment by otaviojava** [comment]
I've created a PR: https://github.com/eclipse/jnosql-diana-driver/pull/123
Could you test this?

**Comment by mxmind** [comment]
@otaviojava yes of course

**Comment by mxmind** [comment]
@otaviojava could you advise me, where I can find the latest snapshot? The [sonatype repository](https://oss.sonatype.org/content/repositories/snapshots/org/jnosql/diana/diana-driver/) does not contain the latest 0.0.9-SNAPSHOT version

**Comment by otaviojava** [comment]
Updated: 
https://oss.sonatype.org/content/repositories/snapshots/org/jnosql/diana/diana-driver/

**Comment by mxmind** [comment]
Hi @otaviojava, 
thank you so much, it works like a charm :)
When do you plan to update the artemis extension?

<img width="911" alt="  kkbdl  Evaluate" src="https://user-images.githubusercontent.com/1923314/55825693-2d0d6380-5b0f-11e9-825c-e28ec95e82e0.png">

**Comment by otaviojava** [comment]
Today :+1:

**Comment by otaviojava** [comment]
I've updated as Snapshot as well; I'll close this one. If you have any more trouble, feel free to open it again.
