### ISSUE TITLE
 Native ArangoDB driver uses the type metadata which might cause class cast exception

### ISSUE THREAD

**Issue by mxmind** [eclipse/jnosql-diana-driver#122]
Hi,
If the document stored in a database has type metadata, it might cause an exception, while the document is being read by Diana driver. The native java driver can use the type metadata, stored in the `_class` attribute. If such attribute presents in a document, the native driver uses it to create an instance of this class. The result is ClassCastException when Diana driver tries to read the returned documents from AQL because it always expects BaseDocument.

An example:
```
{
  ...
  "_class": "io.t.c.o.InventoryType"
}
```
will produce:
`Caused by: java.lang.ClassCastException: class io.t.c.o.InventoryType cannot be cast to class com.arangodb.entity.BaseDocument`

Not tested yet, but this might be the issue when the AQL will return the single value which is not a document, or even the scalar value.

We heavily use such feature to implement a single-collection inheritance strategy.

**Comment by otaviojava** [comment]
What do you think about this option:

https://github.com/eclipse/jnosql-diana-driver/issues/121#issuecomment-480582513

```
<T> List<T> aql(String query, Map<String, Object> values, Class<T> typeClass);
```

**Comment by otaviojava** [comment]
I got a better idea. 
Once that is JSON at the end, I can convert it to JSON and then to the entity that I want.

ps: If you have any specific test to put on the unit test, that could be nice.
I'll work on it.

**Comment by otaviojava** [comment]
Hey, @mxmind Could you give me the `InventoryTyp` structure?

I tried to do this:

```java
ArangoDB arangoDB = ...;
arangoDB.db(DATABASE).collection(COLLECTION_NAME).insertDocument(new Person());
DocumentQuery select = select().from(COLLECTION_NAME).build();
List<DocumentEntity> entities = entityManager.select(select);
```
I did not have any issues, because the BaseDocument work as a JSON structure.


```java
public class Person {

    private String name = "Ada";

    private String city = "London";

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
}
```

**Comment by mxmind** [comment]
Hi @otaviojava, yes of course, I will create an a simple app with unit tests. The issue is not present until you store a class type information in document. I tested on the legacy dataset, where each document has a _class attribute. After removing given attribute everything works as expected, but still has the issue, when I'm trying to select the single scalar value. In my case, we need to obtain the quantity of some particular SKU or some other average value, which is not a document, but derived from document attributes.

**Comment by otaviojava** [comment]
@mxmind this one become duplicated. I'll close, if that is not duplicated, please, feel free to open it again.
