### ISSUE TITLE
Fix the description

### ISSUE THREAD

**Issue by keilw** [eclipse/jnosql-diana-driver#134]
The repository description says "This project contains all implementations from Eclipse JNoSQL Diana-API", it should say "This project contains implementations of Jakarta NoSQL" or similar.

**Comment by otaviojava** [comment]
Thank you @keilw https://bugs.eclipse.org/bugs/show_bug.cgi?id=549151

**Comment by otaviojava** [comment]
@keilw done, what do you think?
