### ISSUE TITLE
Arangodb host splitting

### ISSUE THREAD

**Issue by avaldor-dw** [eclipse/jnosql-diana-driver#137]
Hello,
There is an issue in Class org.jnosql.diana.arangodb.ArangoDBBuilders, into the following method:

 `   private static void host(ArangoDBBuilder arangoDB, String host) {
        final String[] values = host.split(":");
        arangoDB.host(values[0], Integer.valueOf(values[0]));
    }
`

it should be ` Integer.valueOf(value[1])` in the second paramerter of `host` method.

**Comment by otaviojava** [comment]
Thank you @avaldor-dw I'm working on it.

**Comment by otaviojava** [comment]
https://github.com/eclipse/jnosql-diana-driver/pull/138

**Comment by otaviojava** [comment]
Thank you @avaldor-dw fixed.
