### ISSUE TITLE
We should update mongodb java driver for 3.4?

### ISSUE THREAD

**Issue by brenopessoa** [eclipse/jnosql-diana-driver#27]
Please check it's worth, and if agree with that, i'll do a PR

http://mongodb.github.io/mongo-java-driver/3.4/whats-new/

http://mongodb.github.io/mongo-java-driver/3.4/upgrading/

**Comment by otaviojava** [comment]
Hey Breno.
Yes, wen can update to this driver version.

**Comment by otaviojava** [comment]
Done.
