### ISSUE TITLE
Update Redis Driver to use the Standard to JSON

### ISSUE THREAD

**Issue by brenopessoa** [eclipse/jnosql-diana-driver#30]
https://github.com/eclipse/jnosql-diana-driver/issues/29

**Comment by brenopessoa** [comment]
@otaviojava  you can assignee this issue for me.
Thank's

**Comment by otaviojava** [comment]
@brenopessoa you can use this one as reference: https://github.com/eclipse/jnosql-diana-driver/pull/32
