### ISSUE TITLE
Start the application and run scripts to initialize MongoDB database

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql-diana-driver#42]
Is It possible to create a mechanism to execute DDL/DML in MongoDB on application startup?

I would like start the application and run scripts to initialize database, e.g:
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html

@jfelipeoliveira90

**Comment by almeidaah** [comment]
Hi Otavio, one thing that you can do is to create a proprerty that runs MongoDB scripts before initialization. Looke at this solution here: https://github.com/hzpz/mongeez-spring-boot-starter

**Comment by furlaneto** [comment]
I was looking in the MongoDB driver, but there is no more an option to execute native queries.

Since version 3 the function **eval** from Mongo is **deprecated** (https://jira.mongodb.org/browse/JAVA-1782)

**Comment by otaviojava** [comment]
@almeidaah one thing that we can study is how to do that using the query from JNoSQL itself.

What do you think?

**Comment by furlaneto** [comment]
In **diana-mongodb.properties** we can create a new property call something like **mongodb-script-?** and put the file path with the scripts.
```
mongodb-server-host-1=localhost:27017
mongodb-script-1=inserts.jnosql
mongodb-script-2=
```

And we can use JNoSQL query to insert/update

**inserts.jnosql**
```
insert God (name = "Diana", age = 10)
insert God (name = "Artemis", age = 9)
```

**Comment by otaviojava** [comment]
Some thoughts:

* That would be amazing if another NoSQL database uses this.
* We need to figure out one way to just send it once.

Maybe just a utilitarian class.

**Comment by furlaneto** [comment]
@otaviojava I think all NoSQL databases that JNoSQL Aphrodite can work is eligible to have a feature like this.

But if we have to control something like de execution time or another thing like this, could be a external library that uses JNoSQL, because this is not the main ideia of the spec.

**Comment by brenopessoa** [comment]
Yes , i know

the data loading make more sense to think to adopt.
in case of "schema" generation i mean a initial , but flexible schema for
example to  initialize the bucket's , a minimal document.

2018-06-07 12:25 GMT-03:00 Lucas Furlaneto <notifications@github.com>:

**Comment by almeidaah** [comment]
@otaviojava seems good join the @furlaneto and @brenopessoa proposals. Putting some init-script on start to run the 'DDL' scripts along with the predefined words to select schema generating strategy. I'll take a look in the project on the weekend and come back with more comments about it.
