### ISSUE TITLE
The Mongo driver should provide a way to configure authentication

### ISSUE THREAD

**Issue by DaniloAndrade** [eclipse/jnosql-diana-driver#43]
In the MongoClient class it is possible to inform a MongoCrendential list, but in the MongoDBDocumentConfiguration class it is not predicting the configuration of this information 

`public MongoClient(final List<ServerAddress> seeds, final List<MongoCredential> credentialsList)`

**Comment by otaviojava** [comment]
The class MongoClient has several constructors.
So, to I solve that, I'll create a method that receives that MongoClient already defined.

**Comment by otaviojava** [comment]
Please, feel free to give your opinion about this solution.
We'll release the version 0.0.3, perhaps, the next week.
Thank you, for your help.

**Comment by DaniloAndrade** [comment]
This  solution is  Ok for me.
Thank you
