### ISSUE TITLE
ClassNotFoundException: javax.json.bind.JsonbBuilder - Riak Driver

### ISSUE THREAD

**Issue by jfelipeoliveira90** [eclipse/jnosql-diana-driver#47]
The following exception is occurring **"ClassNotFoundException: javax.json.bind.JsonbBuilder"** in the RiakKeyValueEntityManagerFactory class for lack of implementation of **javax.json.bind.Jsonb**. To resolve the issue, add the following dependency to your project:

```
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>1.0</version>
</dependency>

<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.json</artifactId>
    <version>1.1</version>
</dependency>
```

**Comment by otaviojava** [comment]
Hey @jfelipeoliveira90  you're right.
These APIs belongs to Java EE API, that why we define these dependencies as provided. 
What do you think of us provide documentation about this?

**Comment by jfelipeoliveira90** [comment]
Hi @otaviojava .
Challenge accepted 👊

**Comment by otaviojava** [comment]
This site has a documentation about this JSR:
http://json-b.net/
http://json-b.net/users-guide.html
