### ISSUE TITLE
Connect to the ES(Elasticsearch) via http

### ISSUE THREAD

**Issue by jfelipeoliveira90** [eclipse/jnosql-diana-driver#62]
Some services in the cloud do not support the connection to the ES via transport protocol, being necessary to connect via API REST.

It would be good to implement this connection.

Note: TransportClient java will be deprecating in version 7.0 and will be completely removed in version 8.0.

**Comment by furlaneto** [comment]
Yeah, I think adding http connection would be good because if we use some services like AWS, maybe it's the only option to connect.

**Comment by otaviojava** [comment]
@jfelipeoliveira90 IMHO, remove this and add a Rest connection is the best option.

**Comment by furlaneto** [comment]
I saw that Elastic has theirs Http Clients and we could use it.
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html

**Comment by otaviojava** [comment]
Fixed.
Thank you @jfelipeoliveira90  @furlaneto
